const ADD_SEARCH_TAG = 'ADD_SEARCH_TAG';
const REMOVE_SEARCH_TAG = 'REMOVE_SEARCH_TAG';
const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

export {
  ADD_SEARCH_TAG,
  REMOVE_SEARCH_TAG,
  UPDATE_SEARCH_TERM,
};
